// db/seeds/minnaSeed.js
// Struktur 50 Bab Kurikulum Kosakata & Tata Bahasa Gaya Minna no Nihongo (Bab 1–50)

export const MINNA_CHAPTERS = [
  {
    bab: 'Bab 1',
    title: 'Perkenalan Diri & Salam',
    sort_order: 1,
    words: [
      { word: 'わたし', reading: 'watashi', meaning_id: 'Saya', sentence: 'わたしは がくせいです。', translation: 'Saya adalah mahasiswa.' },
      { word: 'あなた', reading: 'anata', meaning_id: 'Anda / Kamu', sentence: 'あなたは せんせいですか。', translation: 'Apakah Anda seorang guru?' },
      { word: 'がくせい', reading: 'gakusei', meaning_id: 'Mahasiswa / Murid', sentence: 'かれは がくせいです。', translation: 'Dia adalah mahasiswa.' },
      { word: 'せんせい', reading: 'sensei', meaning_id: 'Guru / Dosen', sentence: 'たなかせんせいは やさしいです。', translation: 'Guru Tanaka ramah.' },
      { word: 'かいしゃいん', reading: 'kaishain', meaning_id: 'Karyawan perusahaan', sentence: 'ちちは かいしゃいんです。', translation: 'Ayah saya karyawan kantor.' },
      { word: 'じん', reading: 'jin', meaning_id: 'Orang (kebangsaan)', sentence: 'わたしは インドネシアじんです。', translation: 'Saya orang Indonesia.' },
    ],
  },
  {
    bab: 'Bab 2',
    title: 'Benda di Sekitar & Penunjuk Kore/Sore/Are',
    sort_order: 2,
    words: [
      { word: 'これ', reading: 'kore', meaning_id: 'Ini (dekat pembicara)', sentence: 'これは ほんです。', translation: 'Ini adalah buku.' },
      { word: 'それ', reading: 'sore', meaning_id: 'Itu (dekat lawan bicara)', sentence: 'それは なんですか。', translation: 'Itu apa?' },
      { word: 'あれ', reading: 'are', meaning_id: 'Itu (jauh dari keduanya)', sentence: 'あれは くるまです。', translation: 'Itu adalah mobil.' },
      { word: 'ほん', reading: 'hon', meaning_id: 'Buku', sentence: 'にほんごの ほんです。', translation: 'Buku bahasa Jepang.' },
      { word: 'じしょ', reading: 'jisho', meaning_id: 'Kamus', sentence: 'これは じしょです。', translation: 'Ini adalah kamus.' },
      { word: 'かぎ', reading: 'kagi', meaning_id: 'Kunci', sentence: 'くるまの かぎです。', translation: 'Kunci mobil.' },
    ],
  },
  {
    bab: 'Bab 3',
    title: 'Tempat, Lokasi & Arah',
    sort_order: 3,
    words: [
      { word: 'ここ', reading: 'koko', meaning_id: 'Sini (tempat ini)', sentence: 'ここは きょうしつです。', translation: 'Di sini adalah ruang kelas.' },
      { word: 'そこ', reading: 'soko', meaning_id: 'Situ (tempat itu)', sentence: 'そこは ロビーです。', translation: 'Di situ adalah lobi.' },
      { word: 'あそこ', reading: 'asoko', meaning_id: 'Sana (tempat di kejauhan)', sentence: 'あそこは うけつけです。', translation: 'Di sana adalah bagian resepsionis.' },
      { word: 'どこ', reading: 'doko', meaning_id: 'Mana / Di mana', sentence: 'トイレは どこですか。', translation: 'Toilet di mana?' },
      { word: 'きょうしつ', reading: 'kyoushitsu', meaning_id: 'Ruang kelas', sentence: 'きょうしつに はいります。', translation: 'Masuk ke ruang kelas.' },
      { word: 'しょくどう', reading: 'shokudou', meaning_id: 'Kantin / Ruang makan', sentence: 'しょくどうで たべます。', translation: 'Makan di kantin.' },
    ],
  },
  {
    bab: 'Bab 4',
    title: 'Waktu, Jam & Hari',
    sort_order: 4,
    words: [
      { word: 'いま', reading: 'ima', meaning_id: 'Sekarang', sentence: 'いま なんじですか。', translation: 'Sekarang jam berapa?' },
      { word: 'じ', reading: 'ji', meaning_id: 'Pukul / Jam', sentence: 'いま しちじです。', translation: 'Sekarang jam tujuh.' },
      { word: 'ふん', reading: 'fun', meaning_id: 'Menit', sentence: 'じゅっぷん やすみます。', translation: 'Istirahat 10 menit.' },
      { word: 'あさ', reading: 'asa', meaning_id: 'Pagi', sentence: 'まいあさ ろくじに おきます。', translation: 'Setiap pagi bangun jam enam.' },
      { word: 'ひる', reading: 'hiru', meaning_id: 'Siang', sentence: 'おひるごはんを たべます。', translation: 'Makan siang.' },
      { word: 'ばん', reading: 'ban', meaning_id: 'Malam', sentence: 'まいばん べんきょうします。', translation: 'Setiap malam belajar.' },
    ],
  },
  {
    bab: 'Bab 5',
    title: 'Perpindahan & Alat Transportasi',
    sort_order: 5,
    words: [
      { word: 'いきます', reading: 'ikimasu', meaning_id: 'Pergi', sentence: 'とうきょうへ いきます。', translation: 'Pergi ke Tokyo.' },
      { word: 'きます', reading: 'kimasu', meaning_id: 'Datang', sentence: 'ともだちが うちへ きます。', translation: 'Teman datang ke rumah.' },
      { word: 'かえります', reading: 'kaerimasu', meaning_id: 'Pulang', sentence: 'ろくじに うちへ かえります。', translation: 'Pulang ke rumah jam enam.' },
      { word: 'でんしゃ', reading: 'densha', meaning_id: 'Kereta listrik', sentence: 'でんしゃで がっこうへ いきます。', translation: 'Pergi ke sekolah naik kereta.' },
      { word: 'ひこうき', reading: 'hikouki', meaning_id: 'Pesawat terbang', sentence: 'ひこうきで にほんへ きました。', translation: 'Datang ke Jepang naik pesawat.' },
    ],
  },
  {
    bab: 'Bab 6',
    title: 'Aksi Objek, Makanan & Minuman',
    sort_order: 6,
    words: [
      { word: 'たべます', reading: 'tabemasu', meaning_id: 'Makan', sentence: 'パンを たべます。', translation: 'Makan roti.' },
      { word: 'のみます', reading: 'nomimasu', meaning_id: 'Minum', sentence: 'みずを のみます。', translation: 'Minum air.' },
      { word: 'みます', reading: 'mimasu', meaning_id: 'Melihat / Menonton', sentence: 'えいがを みます。', translation: 'Menonton film.' },
      { word: 'ききます', reading: 'kikimasu', meaning_id: 'Mendengar / Bertanya', sentence: 'おんがくを ききます。', translation: 'Mendengarkan musik.' },
      { word: 'ごはん', reading: 'gohan', meaning_id: 'Nasi / Makanan', sentence: 'あさごはんを たべました。', translation: 'Sudah sarapan.' },
    ],
  },
  {
    bab: 'Bab 7',
    title: 'Alat, Sarana & Memberi/Menerima',
    sort_order: 7,
    words: [
      { word: 'きります', reading: 'kirimasu', meaning_id: 'Memotong', sentence: 'ナイフで にくを きります。', translation: 'Memotong daging dengan pisau.' },
      { word: 'あげます', reading: 'agemasu', meaning_id: 'Memberi', sentence: 'ともだちに プレゼントを あげます。', translation: 'Memberikan hadiah kepada teman.' },
      { word: 'もらいます', reading: 'moraimasu', meaning_id: 'Menerima', sentence: 'ははから てがみを もらいました。', translation: 'Menerima surat dari ibu.' },
      { word: 'て', reading: 'te', meaning_id: 'Tangan', sentence: 'てを あらいます。', translation: 'Mencuci tangan.' },
      { word: 'はさみ', reading: 'hasami', meaning_id: 'Gunting', sentence: 'はさみで かみを きります。', translation: 'Memotong kertas dengan gunting.' },
    ],
  },
  {
    bab: 'Bab 8',
    title: 'Kata Sifat I & Na (Keadaan & Sifat)',
    sort_order: 8,
    words: [
      { word: 'おおきい', reading: 'ookii', meaning_id: 'Besar', sentence: 'このへやは おおきいです。', translation: 'Kamar ini besar.' },
      { word: 'ちいさい', reading: 'chiisai', meaning_id: 'Kecil', sentence: 'ちいさい くるまです。', translation: 'Mobil kecil.' },
      { word: 'たかい', reading: 'takai', meaning_id: 'Tinggi / Mahal', sentence: 'この時計は たかいです。', translation: 'Jam ini mahal.' },
      { word: 'やすい', reading: 'yasui', meaning_id: 'Murah', sentence: 'そのシャツは やすいです。', translation: 'Kemeja itu murah.' },
      { word: 'しずか', reading: 'shizuka', meaning_id: 'Tenang / Sunyi', sentence: 'としょかんは しずかです。', translation: 'Perpustakaan itu tenang.' },
      { word: 'きれい', reading: 'kirei', meaning_id: 'Cantik / Bersih', sentence: 'さくらが きれいです。', translation: 'Bunga sakura sangat indah.' },
    ],
  },
  {
    bab: 'Bab 9',
    title: 'Kesukaan, Kemampuan & Kepemilikan',
    sort_order: 9,
    words: [
      { word: 'すき', reading: 'suki', meaning_id: 'Suka / Gemar', sentence: 'にほんの りょうりが すきです。', translation: 'Saya suka masakan Jepang.' },
      { word: 'きらい', reading: 'kirai', meaning_id: 'Tidak suka / Benci', sentence: 'さかなが きらいです。', translation: 'Saya tidak suka ikan.' },
      { word: 'じょうず', reading: 'jouzu', meaning_id: 'Pintar / Mahir', sentence: 'かれは うたが じょうずです。', translation: 'Dia pandai bernyanyi.' },
      { word: 'へた', reading: 'heta', meaning_id: 'Kurang mahir', sentence: 'サッカーが へたです。', translation: 'Saya kurang pandai sepak bola.' },
      { word: 'わかります', reading: 'wakarimasu', meaning_id: 'Mengerti / Paham', sentence: 'にほんごが わかります。', translation: 'Saya mengerti bahasa Jepang.' },
    ],
  },
  {
    bab: 'Bab 10',
    title: 'Keberadaan Makhluk & Posisi Ruang',
    sort_order: 10,
    words: [
      { word: 'あります', reading: 'arimasu', meaning_id: 'Ada (benda mati)', sentence: 'つくえの うえに ほんが あります。', translation: 'Di atas meja ada buku.' },
      { word: 'います', reading: 'imasu', meaning_id: 'Ada (makhluk hidup)', sentence: 'にわに いぬが います。', translation: 'Di halaman ada anjing.' },
      { word: 'うえ', reading: 'ue', meaning_id: 'Atas', sentence: 'はこの うえに あります。', translation: 'Ada di atas kotak.' },
      { word: 'した', reading: 'shita', meaning_id: 'Bawah', sentence: 'つくえの したに ねこが います。', translation: 'Di bawah meja ada kucing.' },
      { word: 'なか', reading: 'naka', meaning_id: 'Dalam', sentence: 'かばんの なかに いれます。', translation: 'Masukkan ke dalam tas.' },
    ],
  },
  {
    bab: 'Bab 11',
    title: 'Satuan Hitung & Kuantitas',
    sort_order: 11,
    words: [
      { word: 'ひとつ', reading: 'hitotsu', meaning_id: 'Satu buah', sentence: 'りんごを ひとつ ください。', translation: 'Tolong beri saya satu apel.' },
      { word: 'ふたつ', reading: 'futatsu', meaning_id: 'Dua buah', sentence: 'みかんを ふたつ かいました。', translation: 'Membeli dua jeruk.' },
      { word: 'ひとり', reading: 'hitori', meaning_id: 'Satu orang / Sendiri', sentence: 'ひとりで いきます。', translation: 'Pergi sendirian.' },
      { word: 'ふたり', reading: 'futari', meaning_id: 'Dua orang', sentence: 'ふたりで たべました。', translation: 'Makan berdua.' },
      { word: 'まい', reading: 'mai', meaning_id: 'Lembar (benda tipis)', sentence: 'きってを さんまい ください。', translation: 'Tolong beri tiga lembar perangko.' },
    ],
  },
  {
    bab: 'Bab 12',
    title: 'Bentuk Lampau Sifat & Perbandingan',
    sort_order: 12,
    words: [
      { word: 'あめ', reading: 'ame', meaning_id: 'Hujan', sentence: 'きのうは あめでした。', translation: 'Kemarin hujan.' },
      { word: 'ゆき', reading: 'yuki', meaning_id: 'Salju', sentence: 'ふゆは ゆきが ふります。', translation: 'Musim dingin turun salju.' },
      { word: 'あたたかい', reading: 'atatakai', meaning_id: 'Hangat', sentence: 'きょうは あたたかいです。', translation: 'Hari ini hangat.' },
      { word: 'すずしい', reading: 'suzushii', meaning_id: 'Sejuk', sentence: 'あきは すずしいです。', translation: 'Musim gugur sejuk.' },
      { word: 'ずっと', reading: 'zutto', meaning_id: 'Jauh lebih', sentence: 'こちらが ずっと いいです。', translation: 'Yang ini jauh lebih bagus.' },
    ],
  },
  {
    bab: 'Bab 13',
    title: 'Keinginan (~tai) & Tujuan Perjalanan',
    sort_order: 13,
    words: [
      { word: 'ほしい', reading: 'hoshii', meaning_id: 'Ingin (benda)', sentence: 'あたらしい くるまが ほしいです。', translation: 'Saya ingin mobil baru.' },
      { word: 'あそびます', reading: 'asobimasu', meaning_id: 'Bermain / Refreshing', sentence: 'うみへ あそびに いきます。', translation: 'Pergi bermain ke pantai.' },
      { word: 'およぎます', reading: 'oyogimasu', meaning_id: 'Berenang', sentence: 'プールで およぎたいです。', translation: 'Saya ingin berenang di kolam renang.' },
      { word: 'つかれます', reading: 'tsukaremasu', meaning_id: 'Lelah / Capek', sentence: 'きょうは とても つかれました。', translation: 'Hari ini sangat lelah.' },
      { word: 'かいもの', reading: 'kaimono', meaning_id: 'Belanja', sentence: 'デパートへ かいものに いきます。', translation: 'Pergi berbelanja ke toserba.' },
    ],
  },
  {
    bab: 'Bab 14',
    title: 'Bentuk -Te & Permintaan Tolong (~te kudasai)',
    sort_order: 14,
    words: [
      { word: 'つけます', reading: 'tsukemasu', meaning_id: 'Menyalakan', sentence: 'でんきを つけて ください。', translation: 'Tolong nyalakan lampu.' },
      { word: 'けします', reading: 'keshimasu', meaning_id: 'Mematikan / Menghapus', sentence: 'エアコンを けして ください。', translation: 'Tolong matikan AC.' },
      { word: 'あけます', reading: 'akemasu', meaning_id: 'Membuka', sentence: 'まどを あけて ください。', translation: 'Tolong buka jendela.' },
      { word: 'しめます', reading: 'shimemasu', meaning_id: 'Menutup', sentence: 'ドアを しめて ください。', translation: 'Tolong tutup pintu.' },
      { word: 'まちます', reading: 'machimasu', meaning_id: 'Menunggu', sentence: 'ちょっと まって ください。', translation: 'Tolong tunggu sebentar.' },
    ],
  },
  {
    bab: 'Bab 15',
    title: 'Izin (~te mo ii) & Larangan (~te wa ikemasen)',
    sort_order: 15,
    words: [
      { word: 'すわります', reading: 'suwarimasu', meaning_id: 'Duduk', sentence: 'ここに すわっても いいですか。', translation: 'Bolehkah saya duduk di sini?' },
      { word: 'たちます', reading: 'tachimasu', meaning_id: 'Berdiri', sentence: 'そこに たっては いけません。', translation: 'Tidak boleh berdiri di situ.' },
      { word: 'つかいます', reading: 'tsukaimasu', meaning_id: 'Menggunakan / Memakai', sentence: 'このペンを つかっても いいです。', translation: 'Boleh menggunakan pulpen ini.' },
      { word: 'すみます', reading: 'sumimasu', meaning_id: 'Tinggal / Menetap', sentence: 'ジャカルタに すんでいます。', translation: 'Tinggal di Jakarta.' },
      { word: 'しります', reading: 'shirimasu', meaning_id: 'Mengetahui / Kenal', sentence: 'その ニュースを しっています。', translation: 'Saya tahu berita itu.' },
    ],
  },
  {
    bab: 'Bab 16',
    title: 'Urutan Aktivitas (~te kara) & Bagian Tubuh',
    sort_order: 16,
    words: [
      { word: 'おります', reading: 'orimasu', meaning_id: 'Turun (dari kendaraan)', sentence: 'つぎの えきで おります。', translation: 'Turun di stasiun berikutnya.' },
      { word: 'のりかえます', reading: 'norikaemasu', meaning_id: 'Pindah jalur / Transit', sentence: 'ここで ちかてつに のりかえます。', translation: 'Transit ke kereta bawah tanah di sini.' },
      { word: 'あたま', reading: 'atama', meaning_id: 'Kepala', sentence: 'あたまが いたいです。', translation: 'Kepala saya sakit.' },
      { word: 'め', reading: 'me', meaning_id: 'Mata', sentence: 'めが わるいです。', translation: 'Mata saya kurang baik.' },
      { word: 'あし', reading: 'ashi', meaning_id: 'Kaki', sentence: 'あしが ながいです。', translation: 'Kakinya panjang.' },
    ],
  },
  {
    bab: 'Bab 17',
    title: 'Bentuk -Nai & Keharusan (~nakereba narimasen)',
    sort_order: 17,
    words: [
      { word: 'わすれます', reading: 'wasuremasu', meaning_id: 'Lupa', sentence: 'しゅくだいを わすれないで ください。', translation: 'Jangan lupa PR-mu.' },
      { word: 'なくします', reading: 'nakushimasu', meaning_id: 'Kehilangan', sentence: 'パスポートを なくさないで ください。', translation: 'Jangan sampai kehilangan paspor.' },
      { word: 'はらいます', reading: 'haraimasu', meaning_id: 'Membayar', sentence: 'おかねを はらわなければ なりません。', translation: 'Harus membayar uang.' },
      { word: 'ぬぎます', reading: 'nugimasu', meaning_id: 'Melepas (pakaian/sepatu)', sentence: 'くつを ぬいで ください。', translation: 'Tolong lepas sepatu.' },
      { word: 'もっていきます', reading: 'motteikimasu', meaning_id: 'Membawa pergi', sentence: 'かさを もっていきます。', translation: 'Membawa payung.' },
    ],
  },
  {
    bab: 'Bab 18',
    title: 'Bentuk Kamus, Kemampuan & Hobi',
    sort_order: 18,
    words: [
      { word: 'できます', reading: 'dekimasu', meaning_id: 'Bisa / Mampu', sentence: 'スキーが できます。', translation: 'Saya bisa main ski.' },
      { word: 'あらいます', reading: 'araimasu', meaning_id: 'Mencuci', sentence: 'てを あらう ことが できます。', translation: 'Bisa mencuci tangan.' },
      { word: 'ひきます', reading: 'hikimasu', meaning_id: 'Memainkan (alat musik petik/tuts)', sentence: 'ピアノを ひく ことが できます。', translation: 'Bisa bermain piano.' },
      { word: 'うたいます', reading: 'utaimasu', meaning_id: 'Bernyanyi', sentence: 'にほんの うたを うたいます。', translation: 'Menyanyikan lagu Jepang.' },
      { word: 'しゅみ', reading: 'shumi', meaning_id: 'Hobi', sentence: 'わたしの しゅみは どくしょです。', translation: 'Hobi saya membaca buku.' },
    ],
  },
  {
    bab: 'Bab 19',
    title: 'Bentuk -Ta & Pengalaman (~ta koto ga aru)',
    sort_order: 19,
    words: [
      { word: 'のぼります', reading: 'noborimasu', meaning_id: 'Mendaki', sentence: 'ふじさんに のぼった ことが あります。', translation: 'Saya pernah mendaki Gunung Fuji.' },
      { word: 'とまります', reading: 'tomarimasu', meaning_id: 'Menginap', sentence: 'ホテルに とまります。', translation: 'Menginap di hotel.' },
      { word: 'そうじします', reading: 'soujishimasu', meaning_id: 'Membersihkan', sentence: 'へやを そうじしました。', translation: 'Sudah membersihkan kamar.' },
      { word: 'せんたくします', reading: 'sentakushimasu', meaning_id: 'Mencuci baju', sentence: 'ふくを せんたくします。', translation: 'Mencuci pakaian.' },
      { word: 'なります', reading: 'narimasu', meaning_id: 'Menjadi', sentence: 'いしゃに なりたいです。', translation: 'Saya ingin menjadi dokter.' },
    ],
  },
  {
    bab: 'Bab 20',
    title: 'Gaya Santai & Percakapan Kasual (Futsuukei)',
    sort_order: 20,
    words: [
      { word: 'いる', reading: 'iru', meaning_id: 'Butuh / Perlu', sentence: 'ビザが いる？', translation: 'Apakah butuh visa?' },
      { word: 'しらべる', reading: 'shiraberu', meaning_id: 'Memeriksa / Mencari tahu', sentence: 'じしょで しらべる。', translation: 'Mencari tahu di kamus.' },
      { word: 'なおす', reading: 'naosu', meaning_id: 'Memperbaiki', sentence: 'くるまを なおす。', translation: 'Memperbaiki mobil.' },
      { word: 'ぼく', reading: 'boku', meaning_id: 'Aku (laki-laki santai)', sentence: 'ぼくも いくよ。', translation: 'Aku juga ikut ya.' },
      { word: 'きみ', reading: 'kimi', meaning_id: 'Kamu (santai)', sentence: 'きみは どう おもう？', translation: 'Bagaimana menurutmu?' },
    ],
  },
  {
    bab: 'Bab 21',
    title: 'Pendapat (~to omoimasu) & Kutipan Kalimat',
    sort_order: 21,
    words: [
      { word: 'おもいます', reading: 'omoimasu', meaning_id: 'Berpikir / Mengira', sentence: 'あしたは あめだと おもいます。', translation: 'Saya kira besok hujan.' },
      { word: 'いいます', reading: 'iimasu', meaning_id: 'Berkata / Mengucapkan', sentence: 'せんせいは テストがあると いいました。', translation: 'Guru berkata bahwa ada ujian.' },
      { word: 'かちます', reading: 'kachimasu', meaning_id: 'Menang', sentence: 'しあいに かちました。', translation: 'Menang dalam pertandingan.' },
      { word: 'まけます', reading: 'makemasu', meaning_id: 'Kalah', sentence: 'ゲームに まけました。', translation: 'Kalah dalam permainan.' },
      { word: 'やくにたちます', reading: 'yakunitachimasu', meaning_id: 'Bermanfaat / Berguna', sentence: 'このほんは やくにたちます。', translation: 'Buku ini sangat berguna.' },
    ],
  },
  {
    bab: 'Bab 22',
    title: 'Modifikasi Kata Benda / Anak Kalimat',
    sort_order: 22,
    words: [
      { word: 'きます', reading: 'kimasu', meaning_id: 'Memakai (baju)', sentence: 'シャツを きます。', translation: 'Memakai kemeja.' },
      { word: 'はきます', reading: 'hakimasu', meaning_id: 'Memakai (sepatu/celana)', sentence: 'くつを はきます。', translation: 'Memakai sepatu.' },
      { word: 'かぶります', reading: 'kaburimasu', meaning_id: 'Memakai (topi)', sentence: 'ぼうしを かぶります。', translation: 'Memakai topi.' },
      { word: 'かけます', reading: 'kakemasu', meaning_id: 'Memakai (kacamata)', sentence: 'めがねを かけます。', translation: 'Memakai kacamata.' },
      { word: 'うまれます', reading: 'umaremasu', meaning_id: 'Lahir', sentence: 'とうきょうで うまれました。', translation: 'Lahir di Tokyo.' },
    ],
  },
  {
    bab: 'Bab 23',
    title: 'Kondisi Saat (~toki) & Syarat Mutlak (~to)',
    sort_order: 23,
    words: [
      { word: 'ききます', reading: 'kikimasu', meaning_id: 'Bertanya arah', sentence: 'みちを ききます。', translation: 'Bertanya jalan.' },
      { word: 'まわします', reading: 'mawashimasu', meaning_id: 'Memutar', sentence: '右へ まわすと、おとが おおきくなります。', translation: 'Kalau diputar ke kanan, suaranya membesar.' },
      { word: 'ひきます', reading: 'hikimasu', meaning_id: 'Menarik', sentence: 'このドアは ひいて あけます。', translation: 'Pintu ini dibuka dengan ditarik.' },
      { word: 'わたります', reading: 'watarimasu', meaning_id: 'Menyeberang', sentence: 'はしを わたります。', translation: 'Menyeberangi jembatan.' },
      { word: 'まがります', reading: 'magarimasu', meaning_id: 'Berbelok', sentence: 'しんごうを ひだりへ まがります。', translation: 'Belok ke kiri di lampu merah.' },
    ],
  },
  {
    bab: 'Bab 24',
    title: 'Pemberian & Pertolongan (Kureru, Agaru)',
    sort_order: 24,
    words: [
      { word: 'くれます', reading: 'kuremasu', meaning_id: 'Memberi (kepada saya)', sentence: 'ともだちが 本を くれました。', translation: 'Teman memberi buku kepada saya.' },
      { word: 'つれていきます', reading: 'tsureteikimasu', meaning_id: 'Mengajak pergi', sentence: 'こどもを こうえんへ つれていきます。', translation: 'Mengajak anak pergi ke taman.' },
      { word: 'つれてきます', reading: 'tsuretekimasu', meaning_id: 'Membawa serta datang', sentence: 'いぬを つれてきました。', translation: 'Membawa anjing kemari.' },
      { word: 'おくります', reading: 'okurimasu', meaning_id: 'Mengantar / Mengirim', sentence: 'えきまで おくります。', translation: 'Mengantar sampai stasiun.' },
      { word: 'しょうかいします', reading: 'shoukaishimasu', meaning_id: 'Memperkenalkan', sentence: 'ともだちを しょうかいします。', translation: 'Memperkenalkan teman.' },
    ],
  },
  {
    bab: 'Bab 25',
    title: 'Pengandaian Realistis (~tara) & Walaupun (~temo)',
    sort_order: 25,
    words: [
      { word: 'かんがえます', reading: 'kangaemasu', meaning_id: 'Berpikir / Merenung', sentence: 'よく かんがえて ください。', translation: 'Tolong pikirkan baik-baik.' },
      { word: 'つきます', reading: 'tsukimasu', meaning_id: 'Tiba / Sampai', sentence: 'えきに ついたら でんわします。', translation: 'Kalau sudah sampai stasiun saya akan telepon.' },
      { word: 'りゅうがくします', reading: 'ryuugakushimasu', meaning_id: 'Belajar ke luar negeri', sentence: 'にほんへ りゅうがくします。', translation: 'Belajar ke luar negeri ke Jepang.' },
      { word: 'いなか', reading: 'inaka', meaning_id: 'Kampung halaman / Desa', sentence: 'いなかへ かえります。', translation: 'Pulang ke kampung halaman.' },
      { word: 'チャンス', reading: 'chansu', meaning_id: 'Kesempatan', sentence: 'いい チャンスです。', translation: 'Ini kesempatan bagus.' },
    ],
  },
  // Bab 26 - 50: Tingkat Lanjut Dasar / Pra-Menengah (Minna no Nihongo II)
  {
    bab: 'Bab 26',
    title: 'Penjelasan Keadaan Mendalam (~n desu)',
    sort_order: 26,
    words: [
      { word: 'みます', reading: 'mimasu', meaning_id: 'Memeriksa / Mengecek', sentence: 'いしゃに みてもらいます。', translation: 'Diperiksa oleh dokter.' },
      { word: 'さがします', reading: 'sagashimasu', meaning_id: 'Mencari', sentence: 'かぎを さがしているんです。', translation: 'Saya sedang mencari kunci.' },
      { word: 'おくれます', reading: 'okuremasu', meaning_id: 'Terlambat', sentence: 'じかんに おくれたんです。', translation: 'Alasannya karena saya terlambat.' },
      { word: 'まにあいます', reading: 'maniaimasu', meaning_id: 'Sempat / Tepat waktu', sentence: 'でんしゃに まにあいました。', translation: 'Sempat naik kereta tepat waktu.' },
      { word: 'ひろいます', reading: 'hiroimasu', meaning_id: 'Memungut / Menemukan', sentence: 'さいふを ひろいました。', translation: 'Menemukan dompet di jalan.' },
    ],
  },
  {
    bab: 'Bab 27',
    title: 'Kata Kerja Bentuk Potensial (Kanoukei)',
    sort_order: 27,
    words: [
      { word: 'かえます', reading: 'kaemasu', meaning_id: 'Dapat membeli', sentence: 'コンビニで かえます。', translation: 'Bisa dibeli di toserba mini.' },
      { word: 'みえます', reading: 'miemasu', meaning_id: 'Terlihat (secara alami)', sentence: 'まどから ふじさんが みえます。', translation: 'Dari jendela terlihat Gunung Fuji.' },
      { word: 'きこえます', reading: 'kikoemasu', meaning_id: 'Terdengar (secara alami)', sentence: 'なみの おとが きこえます。', translation: 'Terdengar suara ombak.' },
      { word: 'できます', reading: 'dekimasu', meaning_id: 'Selesai dibangun / Jadi', sentence: 'あたらしい えきが できました。', translation: 'Stasiun baru sudah selesai dibangun.' },
      { word: 'ひらきます', reading: 'hirakimasu', meaning_id: 'Membuka kelas / Mengadakan', sentence: 'きょうしつを ひらきます。', translation: 'Membuka kelas kursus.' },
    ],
  },
  {
    bab: 'Bab 28',
    title: 'Aksi Bersamaan (~nagara) & Berulang (~shi)',
    sort_order: 28,
    words: [
      { word: 'うれます', reading: 'uremasu', meaning_id: 'Terjual laku', sentence: 'パンが よく うれます。', translation: 'Rotinya laku keras.' },
      { word: 'おどります', reading: 'odorimasu', meaning_id: 'Menari', sentence: 'おんがくを ききながら おどります。', translation: 'Menari sambil mendengarkan musik.' },
      { word: 'かみます', reading: 'kamimasu', meaning_id: 'Mengunyah / Menggigit', sentence: 'ガムを かみます。', translation: 'Mengunyah permen karet.' },
      { word: 'えらびます', reading: 'erabimasu', meaning_id: 'Memilih', sentence: 'すきな いろを えらびます。', translation: 'Memilih warna yang disukai.' },
      { word: 'まじめ', reading: 'majime', meaning_id: 'Rajin / Sungguh-sungguh', sentence: 'かれは まじめな がくせいです。', translation: 'Dia murid yang rajin dan tekun.' },
    ],
  },
  {
    bab: 'Bab 29',
    title: 'Keadaan Hasil Perubahan Otomatis (Jidoushi)',
    sort_order: 29,
    words: [
      { word: 'あきます', reading: 'akimasu', meaning_id: 'Terbuka', sentence: 'ドアが あいています。', translation: 'Pintunya dalam keadaan terbuka.' },
      { word: 'しまります', reading: 'shimarimasu', meaning_id: 'Tertutup', sentence: 'まどが しまっています。', translation: 'Jendelanya tertutup.' },
      { word: 'つきます', reading: 'tsukimasu', meaning_id: 'Menyala (lampu)', sentence: 'でんきが ついています。', translation: 'Lampunya menyala.' },
      { word: 'きえます', reading: 'kiemasu', meaning_id: 'Padam / Mati', sentence: 'でんきが きえています。', translation: 'Lampunya padam.' },
      { word: 'こわれます', reading: 'kowaremasu', meaning_id: 'Rusak', sentence: 'いすが こわれています。', translation: 'Kursinya rusak.' },
    ],
  },
  {
    bab: 'Bab 30',
    title: 'Persiapan & Kondisi Terencana (~te aru, ~te oku)',
    sort_order: 30,
    words: [
      { word: 'はります', reading: 'harimasu', meaning_id: 'Menempelkan', sentence: 'カレンダーが はってあります。', translation: 'Kalender sudah tertempel di dinding.' },
      { word: 'かけます', reading: 'kakemasu', meaning_id: 'Menggantungkan', sentence: 'コートを かけておきます。', translation: 'Menggantung jas terlebih dahulu.' },
      { word: 'かざります', reading: 'kazarimasu', meaning_id: 'Menghias', sentence: 'はなを かざります。', translation: 'Menghias dengan bunga.' },
      { word: 'ならべます', reading: 'narabemasu', meaning_id: 'Menata berjejer', sentence: 'ほんを ならべておきます。', translation: 'Menata buku-buku berjejer.' },
      { word: 'かたづけます', reading: 'katadukemasu', meaning_id: 'Merapikan', sentence: 'へやを かたづけます。', translation: 'Merapikan kamar.' },
    ],
  },
  {
    bab: 'Bab 31',
    title: 'Bentuk Maksud & Rencana (~ou to omou, ~tsumori)',
    sort_order: 31,
    words: [
      { word: 'はじめます', reading: 'hajimemasu', meaning_id: 'Memulai', sentence: 'かいぎを はじめよう。', translation: 'Mari kita mulai rapatnya.' },
      { word: 'つづけます', reading: 'tsuzukemasu', meaning_id: 'Melanjutkan', sentence: 'べんきょうを つづける つもりです。', translation: 'Saya berencana melanjutkan studi.' },
      { word: 'みつけます', reading: 'mitsukemasu', meaning_id: 'Menemukan', sentence: 'いい しごとを みつけたい。', translation: 'Ingin menemukan pekerjaan yang baik.' },
      { word: 'うけます', reading: 'ukemasu', meaning_id: 'Mengikuti ujian', sentence: 'しけんを うける よていです。', translation: 'Rencananya akan ikut ujian.' },
      { word: 'きゅうけい', reading: 'kyuukei', meaning_id: 'Istirahat sejenak', sentence: 'きゅうけいしましょう。', translation: 'Mari kita istirahat sejenak.' },
    ],
  },
  {
    bab: 'Bab 32',
    title: 'Saran Sopan (~hou ga ii) & Prediksi (~deshou)',
    sort_order: 32,
    words: [
      { word: 'うんどうします', reading: 'undoushimasu', meaning_id: 'Berolahraga', sentence: 'まいにち うんどうした ほうが いいです。', translation: 'Sebaiknya berolahraga setiap hari.' },
      { word: 'せいこうします', reading: 'seikoushimasu', meaning_id: 'Berhasil / Sukses', sentence: 'きっと せいこうするでしょう。', translation: 'Pasti akan berhasil.' },
      { word: 'しっぱいします', reading: 'shippaishimasu', meaning_id: 'Gagal', sentence: 'しけんを しっぱいしました。', translation: 'Gagal dalam ujian.' },
      { word: 'ごうかくします', reading: 'goukaku shimasu', meaning_id: 'Lulus ujian', sentence: 'N5に ごうかくしました。', translation: 'Lulus ujian JLPT N5.' },
      { word: 'やみます', reading: 'yamimasu', meaning_id: 'Reda (hujan/salju)', sentence: 'あめが やむでしょう。', translation: 'Hujannya mungkin akan reda.' },
    ],
  },
  {
    bab: 'Bab 33',
    title: 'Bentuk Perintah & Larangan Tegas (Meireikei)',
    sort_order: 33,
    words: [
      { word: 'にげます', reading: 'nigemasu', meaning_id: 'Kabur / Melarikan diri', sentence: 'あぶない、にげろ！', translation: 'Bahaya, lari!' },
      { word: 'さわぎます', reading: 'sawagimasu', meaning_id: 'Membuat keributan', sentence: 'ここで さわぐな！', translation: 'Jangan membuat ribut di sini!' },
      { word: 'あきらめます', reading: 'akiramemasu', meaning_id: 'Menyerah / Putus asa', sentence: 'さいごまで あきらめるな。', translation: 'Jangan menyerah sampai akhir.' },
      { word: 'なげます', reading: 'nagemasu', meaning_id: 'Melempar', sentence: 'ボールを なげろ。', translation: 'Lempar bolanya.' },
      { word: 'まもります', reading: 'mamarimasu', meaning_id: 'Mematuhi / Menjaga', sentence: 'ルールを まもれ。', translation: 'Patuhi aturannya.' },
    ],
  },
  {
    bab: 'Bab 34',
    title: 'Instruksi Presisi (~toori ni) & Setelah (~ato de)',
    sort_order: 34,
    words: [
      { word: 'みがきます', reading: 'migakimasu', meaning_id: 'Menggosok gigi', sentence: 'ごはんの あとで はを みがきます。', translation: 'Menggosok gigi setelah makan.' },
      { word: 'くみたてます', reading: 'kumitatemasu', meaning_id: 'Merakit', sentence: 'せつめいしょの とおりに くみたてます。', translation: 'Merakit sesuai buku petunjuk.' },
      { word: 'おります', reading: 'orimasu', meaning_id: 'Melipat', sentence: 'かみを はんぶんに おります。', translation: 'Melipat kertas menjadi dua.' },
      { word: 'きがつきます', reading: 'kigatsukimasu', meaning_id: 'Menyadari', sentence: 'まちがいに きがつきました。', translation: 'Menyadari ada kesalahan.' },
      { word: 'つけます', reading: 'tsukemasu', meaning_id: 'Mencelupkan bumbu', sentence: 'しょうゆを つけて たべます。', translation: 'Makan dicelup kecap asin.' },
    ],
  },
  {
    bab: 'Bab 35',
    title: 'Kondisional Hipotesis Formal (~ba, ~nara)',
    sort_order: 35,
    words: [
      { word: 'さきます', reading: 'sakimasu', meaning_id: 'Mekar (bunga)', sentence: 'はるに なれば さくらが さきます。', translation: 'Jika musim semi tiba sakura akan mekar.' },
      { word: 'かわります', reading: 'kawarimasu', meaning_id: 'Berubah', sentence: 'いろが かわります。', translation: 'Warnanya berubah.' },
      { word: 'こまります', reading: 'komarimasu', meaning_id: 'Mengalami kesulitan', sentence: 'おかねが なければ こまります。', translation: 'Jika tidak ada uang akan susah.' },
      { word: 'ひろい', reading: 'hiroi', meaning_id: 'Luas', sentence: 'へやが ひろければ いいですね。', translation: 'Kalau kamarnya luas tentu bagus ya.' },
      { word: 'べんり', reading: 'benri', meaning_id: 'Praktis', sentence: 'ちかてつの ほうが べんりなら のりましょう。', translation: 'Kalau kereta bawah tanah lebih praktis ayo naik.' },
    ],
  },
  {
    bab: 'Bab 36',
    title: 'Usaha Bertahap (~you ni suru) & Perubahan (~you ni naru)',
    sort_order: 36,
    words: [
      { word: 'とどきます', reading: 'todokimasu', meaning_id: 'Sampai (kiriman paket)', sentence: 'にもつが とどきました。', translation: 'Paketnya sudah sampai.' },
      { word: 'ちょきんします', reading: 'chokinshimasu', meaning_id: 'Menabung uang', sentence: 'まいげつ ちょきんするように しています。', translation: 'Saya berusaha menabung setiap bulan.' },
      { word: 'ふとります', reading: 'futorimasu', meaning_id: 'Bertambah gemuk', sentence: 'さいきん ふとりました。', translation: 'Akhir-akhir ini saya bertambah gemuk.' },
      { word: 'やせます', reading: 'yasemasu', meaning_id: 'Menjadi kurus / Langsing', sentence: 'うんどうして やせました。', translation: 'Menjadi langsing setelah olahraga.' },
      { word: 'ならいます', reading: 'naraimasu', meaning_id: 'Mempelajari', sentence: 'かんじが よめるように なりました。', translation: 'Sekarang sudah bisa membaca kanji.' },
    ],
  },
  {
    bab: 'Bab 37',
    title: 'Bentuk Pasif (Ukemi)',
    sort_order: 37,
    words: [
      { word: 'ほめます', reading: 'homemasu', meaning_id: 'Memuji', sentence: 'せんせいに ほめられました。', translation: 'Saya dipuji oleh guru.' },
      { word: 'しかります', reading: 'shikarimasu', meaning_id: 'Memarahi', sentence: 'ははに しかられました。', translation: 'Saya dimarahi oleh ibu.' },
      { word: 'ふみます', reading: 'fumimasu', meaning_id: 'Menginjak', sentence: 'でんしゃで あしを ふまれました。', translation: 'Kaki saya terinjak di dalam kereta.' },
      { word: 'たのみます', reading: 'tanomimasu', meaning_id: 'Meminta tolong / Memesan', sentence: 'しごとを たのまれました。', translation: 'Saya dimintai tolong pekerjaan.' },
      { word: 'はつめいします', reading: 'hatsumeishimasu', meaning_id: 'Menciptakan / Menemukan', sentence: 'でんわは ベルに はつめいされました。', translation: 'Telepon diciptakan oleh Bell.' },
    ],
  },
  {
    bab: 'Bab 38',
    title: 'Nominalisasi Kalimat (~no wa, ~no ga)',
    sort_order: 38,
    words: [
      { word: 'そだてます', reading: 'sodatemasu', meaning_id: 'Memelihara / Membesarkan', sentence: 'はなを そだてるのが すきです。', translation: 'Saya suka merawat bunga.' },
      { word: 'はこびます', reading: 'hakobimasu', meaning_id: 'Mengangkut / Membawa', sentence: 'おもい にもつを はこびます。', translation: 'Mengangkut barang bawaan yang berat.' },
      { word: 'にゅういんします', reading: 'nyuuinshimasu', meaning_id: 'Masuk rumah sakit / Rawat inap', sentence: 'びょういんに にゅういんしました。', translation: 'Dirawat inap di rumah sakit.' },
      { word: 'たいいんします', reading: 'taiinshimasu', meaning_id: 'Keluar dari rumah sakit', sentence: 'らいしゅう たいいんします。', translation: 'Minggu depan keluar dari RS.' },
      { word: 'うそ', reading: 'uso', meaning_id: 'Kebohongan', sentence: 'うそを いうのは よくないです。', translation: 'Berbohong itu tidak baik.' },
    ],
  },
  {
    bab: 'Bab 39',
    title: 'Sebab & Alasan (~te / ~de)',
    sort_order: 39,
    words: [
      { word: 'おどろきます', reading: 'odorokimasu', meaning_id: 'Terkejut / Kaget', sentence: 'ニュースを きいて おどろきました。', translation: 'Saya terkejut mendengar berita itu.' },
      { word: 'がっかりします', reading: 'gakkarishimasu', meaning_id: 'Kecewa', sentence: 'しけんに おちて がっかりしました。', translation: 'Kecewa karena tidak lulus ujian.' },
      { word: 'あんしんします', reading: 'anshinshimasu', meaning_id: 'Lega / Tenang hati', sentence: 'かぞくの かおを みて あんしんしました。', translation: 'Hati lega setelah melihat wajah keluarga.' },
      { word: 'じこ', reading: 'jiko', meaning_id: 'Kecelakaan', sentence: 'じこで でんしゃが とまりました。', translation: 'Kereta berhenti karena kecelakaan.' },
      { word: 'じしん', reading: 'jishin', meaning_id: 'Gempa bumi', sentence: 'きのう おおきい じしんが ありました。', translation: 'Kemarin ada gempa bumi besar.' },
    ],
  },
  {
    bab: 'Bab 40',
    title: 'Pertanyaan Tersirat Tak Langsung (~ka dou ka)',
    sort_order: 40,
    words: [
      { word: 'かぞえます', reading: 'kazoemasu', meaning_id: 'Menghitung', sentence: 'かずを かぞえて ください。', translation: 'Tolong hitung jumlahnya.' },
      { word: 'はかります', reading: 'hakarimasu', meaning_id: 'Mengukur berat/panjang', sentence: 'おもさを はかります。', translation: 'Menimbang beratnya.' },
      { word: 'たしかめます', reading: 'tashikamemasu', meaning_id: 'Memastikan / Memeriksa kembali', sentence: 'じかんを たしかめて ください。', translation: 'Tolong pastikan kembali waktunya.' },
      { word: 'あいます', reading: 'aimasu', meaning_id: 'Cocok / Pas ukurannya', sentence: 'サイズが あいます。', translation: 'Ukurannya pas dan cocok.' },
      { word: 'しゅっぱつします', reading: 'shuppatsushimasu', meaning_id: 'Berangkat', sentence: 'ひこうきが しゅっぱつします。', translation: 'Pesawatnya akan segera berangkat.' },
    ],
  },
  {
    bab: 'Bab 41',
    title: 'Tingkatan Sopan Pemberian (Itadaku, Kudasaru)',
    sort_order: 41,
    words: [
      { word: 'いただきます', reading: 'itadakimasu', meaning_id: 'Menerima (dari atasan/orang dihormati)', sentence: 'しゃちょうから おみやげを いただきました。', translation: 'Saya menerima oleh-oleh dari direktur.' },
      { word: 'くださいます', reading: 'kudasaimasu', meaning_id: 'Memberi (atasan memberi ke saya)', sentence: 'せんせいが 本を くださいました。', translation: 'Guru memberikan buku kepada saya.' },
      { word: 'やります', reading: 'yarimasu', meaning_id: 'Memberi (ke bawahan/hewan/tumbuhan)', sentence: 'いぬに えさを やります。', translation: 'Memberi makan anjing.' },
      { word: 'あげます', reading: 'agemasu', meaning_id: 'Menaikkan', sentence: 'おんどを あげます。', translation: 'Menaikkan suhu.' },
      { word: 'さげます', reading: 'sagemasu', meaning_id: 'Menurunkan', sentence: 'おとを さげてください。', translation: 'Tolong kecilkan suaranya.' },
    ],
  },
  {
    bab: 'Bab 42',
    title: 'Tujuan Tertentu (~tame ni, ~noni tsukau)',
    sort_order: 42,
    words: [
      { word: 'つつみます', reading: 'tsutsumimasu', meaning_id: 'Membungkus', sentence: 'プレゼントを きれいに つつみます。', translation: 'Membungkus hadiah dengan rapi.' },
      { word: 'わかします', reading: 'wakashimasu', meaning_id: 'Merebus / Memanaskan air', sentence: 'おゆを わかします。', translation: 'Merebus air panas.' },
      { word: 'まぜます', reading: 'mazemasu', meaning_id: 'Mencampur / Mengaduk', sentence: 'さとうと ミルクを まぜます。', translation: 'Mengaduk gula dan susu.' },
      { word: 'けいさんします', reading: 'keisanshimasu', meaning_id: 'Menghitung kalkulasi', sentence: 'でんたくで けいさんします。', translation: 'Menghitung memakai kalkulator.' },
      { word: 'べんきょうのため', reading: 'benkyou no tame', meaning_id: 'Demi belajar', sentence: 'しょうらいの ために べんきょうします。', translation: 'Belajar demi masa depan.' },
    ],
  },
  {
    bab: 'Bab 43',
    title: 'Kesan Pandangan (~sou desu) & Titik Kejadian',
    sort_order: 43,
    words: [
      { word: 'ふえます', reading: 'fuemasu', meaning_id: 'Bertambah banyak', sentence: 'ゆしゅつが ふえました。', translation: 'Ekspor telah meningkat.' },
      { word: 'へります', reading: 'herimasu', meaning_id: 'Berkurang', sentence: 'たいじゅうが へりました。', translation: 'Berat badan berkurang.' },
      { word: 'あがります', reading: 'agarimasu', meaning_id: 'Naik (harga/posisi)', sentence: 'ねだんが あがりそうです。', translation: 'Kelihatannya harga akan naik.' },
      { word: 'おちます', reading: 'ochimasu', meaning_id: 'Jatuh', sentence: 'にもつが おちそうです。', translation: 'Barang bawaannya mau jatuh.' },
      { word: 'おいしそう', reading: 'oishisou', meaning_id: 'Tampak lezat', sentence: 'このケーキは おいしそうです。', translation: 'Kue ini kelihatannya sangat lezat.' },
    ],
  },
  {
    bab: 'Bab 44',
    title: 'Berlebihan (~sugiru) & Derajat Kemudahan (~yasui)',
    sort_order: 44,
    words: [
      { word: 'なきます', reading: 'nakimasu', meaning_id: 'Menangis', sentence: 'あかちゃんが ないています。', translation: 'Bayi sedang menangis.' },
      { word: 'わらいます', reading: 'waraimasu', meaning_id: 'Tertawa', sentence: 'みんなで わらいました。', translation: 'Semua tertawa bersama.' },
      { word: 'かわきます', reading: 'kawakimasu', meaning_id: 'Kering', sentence: 'せんたくものが かわきました。', translation: 'Cucian baju sudah kering.' },
      { word: 'ぬれます', reading: 'nuremasu', meaning_id: 'Basah', sentence: 'あめで ぬれました。', translation: 'Basah kuyup karena hujan.' },
      { word: 'たべすぎます', reading: 'tabesugimasu', meaning_id: 'Makan berlebihan', sentence: 'ゆうべ たべすぎました。', translation: 'Tadi malam saya makan terlalu banyak.' },
    ],
  },
  {
    bab: 'Bab 45',
    title: 'Situasi Khusus (~baai wa) & Bertentangan (~noni)',
    sort_order: 45,
    words: [
      { word: 'しんじます', reading: 'shinjimasu', meaning_id: 'Percaya', sentence: 'あなたを しんじています。', translation: 'Saya mempercayai Anda.' },
      { word: 'キャンセルします', reading: 'kyanserushimasu', meaning_id: 'Membatalkan', sentence: 'よやくを キャンセルしました。', translation: 'Membatalkan reservasi.' },
      { word: 'ほしょうしょ', reading: 'hoshousho', meaning_id: 'Surat garansi', sentence: 'ほしょうしょを なくさないでください。', translation: 'Jangan sampai menghilangkan kartu garansi.' },
      { word: 'かじ', reading: 'kaji', meaning_id: 'Kebakaran', sentence: 'かじの ばあいは ひなんしてください。', translation: 'Jika terjadi kebakaran segera evakuasi.' },
      { word: 'べんきょうしたのに', reading: 'benkyou shita noni', meaning_id: 'Padahal sudah belajar', sentence: 'べんきょうしたのに、テストが むずかしかった。', translation: 'Padahal sudah belajar, tetapi ujiannya sulit.' },
    ],
  },
  {
    bab: 'Bab 46',
    title: 'Titik Waktu Tindakan (~tokoro, ~bakari)',
    sort_order: 46,
    words: [
      { word: 'あつまります', reading: 'atsumarimasu', meaning_id: 'Berkumpul', sentence: 'ひとが たくさん あつまっています。', translation: 'Orang-orang berkumpul banyak.' },
      { word: 'わかれます', reading: 'wakaremasu', meaning_id: 'Berpisah', sentence: 'くうこうで ともだちと わかれました。', translation: 'Berpisah dengan teman di bandara.' },
      { word: 'いまから', reading: 'ima kara', meaning_id: 'Mulai sekarang', sentence: 'いまから たべるところです。', translation: 'Saya baru saja mau makan sekarang.' },
      { word: 'たったいま', reading: 'tatta ima', meaning_id: 'Baru saja terjadi', sentence: 'たったいま ついたところです。', translation: 'Saya baru saja tiba detik ini.' },
      { word: 'かったばかり', reading: 'katta bakari', meaning_id: 'Baru saja dibeli', sentence: 'このくるまは かったばかりです。', translation: 'Mobil ini baru saja saya beli.' },
    ],
  },
  {
    bab: 'Bab 47',
    title: 'Penyampaian Kabar (~sou desu, ~rashii)',
    sort_order: 47,
    words: [
      { word: 'あつまります', reading: 'atsumarimasu', meaning_id: 'Berkumpul bersama', sentence: 'かいぎに あつまります。', translation: 'Berkumpul untuk rapat.' },
      { word: 'うわさ', reading: 'uwasa', meaning_id: 'Rumor / Desas-desus', sentence: 'その うわさを ききました。', translation: 'Saya mendengar rumor tersebut.' },
      { word: 'てんきよほう', reading: 'tenki yohou', meaning_id: 'Prakiraan cuaca', sentence: 'てんきよほうに よると、あしたは はれです。', translation: 'Menurut ramalan cuaca, besok cerah.' },
      { word: 'じけん', reading: 'jiken', meaning_id: 'Peristiwa / Kasus insiden', sentence: 'えきの まえで じけんが ありました。', translation: 'Ada insiden di depan stasiun.' },
      { word: 'あめだそうです', reading: 'ame da sou desu', meaning_id: 'Katanya akan hujan', sentence: 'ごごから あめだそうです。', translation: 'Katanya mulai siang akan hujan.' },
    ],
  },
  {
    bab: 'Bab 48',
    title: 'Bentuk Kausatif (Shiekikei / Menyuruh, Mengizinkan)',
    sort_order: 48,
    words: [
      { word: 'ならべます', reading: 'narabemasu', meaning_id: 'Menjajarkan', sentence: 'つくえを ならばせます。', translation: 'Menyuruh menata meja berjajar.' },
      { word: 'まかせます', reading: 'makasemasu', meaning_id: 'Menyerahkan / Mempercayakan', sentence: 'しごとを ぶかに まかせます。', translation: 'Mempercayakan tugas kepada bawahan.' },
      { word: 'いかせます', reading: 'ikasemasu', meaning_id: 'Menyuruh pergi', sentence: 'こどもを じゅくへ いかせます。', translation: 'Menyuruh anak pergi ke tempat les.' },
      { word: 'のませます', reading: 'nomasemasu', meaning_id: 'Meminumkan / Menyuruh minum', sentence: 'くすりを のませます。', translation: 'Meminumkan obat ke pasien.' },
      { word: 'てつだわせます', reading: 'tetsudawasemasu', meaning_id: 'Menyuruh membantu', sentence: 'りょうりを てつだわせます。', translation: 'Menyuruh membantu memasak.' },
    ],
  },
  {
    bab: 'Bab 49',
    title: 'Bahasa Hormat Sonkeigo (Menghormati Lawan Bicara)',
    sort_order: 49,
    words: [
      { word: 'いらっしゃいます', reading: 'irasshaimasu', meaning_id: 'Ada / Pergi / Datang (sopan)', sentence: 'せんせいは きょう きょうしつに いらっしゃいますか。', translation: 'Apakah guru hari ini ada di ruang kelas?' },
      { word: 'めしあがります', reading: 'meshiagarimasu', meaning_id: 'Makan / Minum (sopan)', sentence: 'どうぞ めしあがってください。', translation: 'Silakan dinikmati makanannya.' },
      { word: 'おっしゃいます', reading: 'osshaimasu', meaning_id: 'Berkata / Berbicara (sopan)', sentence: 'しゃちょうは なんと おっしゃいましたか。', translation: 'Apa yang telah disampaikan oleh direktur?' },
      { word: 'ごぞんじです', reading: 'gozonji desu', meaning_id: 'Mengetahui (sopan)', sentence: 'その かたを ごぞんじですか。', translation: 'Apakah Anda mengenal orang tersebut?' },
      { word: 'ごらんになります', reading: 'goran ni narimasu', meaning_id: 'Melihat (sopan)', sentence: 'この しりょうを ごらんになりましたか。', translation: 'Apakah Anda sudah melihat dokumen ini?' },
    ],
  },
  {
    bab: 'Bab 50',
    title: 'Bahasa Rendah Hati Kenjougo (Merendahkan Diri Sendiri)',
    sort_order: 50,
    words: [
      { word: 'まいります', reading: 'mairimasu', meaning_id: 'Pergi / Datang (rendah hati)', sentence: 'ただいま まいりました。', translation: 'Saya baru saja tiba / datang.' },
      { word: 'おります', reading: 'orimasu', meaning_id: 'Ada (rendah hati)', sentence: 'わたしは とうきょうに おります。', translation: 'Saya berada di Tokyo.' },
      { word: 'いただきます', reading: 'itadakimasu', meaning_id: 'Makan / Minum (rendah hati)', sentence: 'おいしく いただきます。', translation: 'Saya nikmati makanan ini.' },
      { word: 'もうします', reading: 'moushimasu', meaning_id: 'Bernama / Berkata (rendah hati)', sentence: 'たなかと もうします。', translation: 'Nama saya Tanaka.' },
      { word: 'いたします', reading: 'itashimasu', meaning_id: 'Melakukan (rendah hati)', sentence: 'わたしが ごあんない いたします。', translation: 'Saya yang akan memandu Anda.' },
    ],
  },
];
